"""Swadesh 207 목록 정의 (영어 기준).

각 항목:
  n      번호 (Swadesh 207 목록 순서)
  en     영어 표제어 (영어 Wiktionary 항목 이름)
  label  화면에 보여 줄 영어 표기
  pos    품사 (영어 항목에서 어느 품사 항목의 번역표를 쓸지)
  core   Swadesh 100 단어 목록(1971)에도 있는 항목인지
  hint   번역표의 sense 문구에 이 정규식이 있는 번역만 쓴다. 영어 항목에 뜻이 여러 개라 번역이 뒤섞이는 단어(bark, right …)를 가르는 용도.
"""

# (n, en, label, pos, core, hint)
_RAW = [
    (1, "I", "I", "pron", True, None),
    (2, "you", "you (singular)", "pron", True, r"subject pronoun: the person"),
    (3, "he", "he", "pron", False, None),
    (4, "we", "we", "pron", True, None),
    (5, "you", "you (plural)", "pron", False, r"subject pronoun: the group"),
    (6, "they", "they", "pron", False, None),
    (7, "this", "this", "det", True, None),
    (8, "that", "that", "det", True, None),
    (9, "here", "here", "adv", False, None),
    (10, "there", "there", "adv", False, None),
    (11, "who", "who", "pron", True, None),
    (12, "what", "what", "pron", True, None),
    (13, "where", "where", "adv", False, None),
    (14, "when", "when", "adv", False, None),
    (15, "how", "how", "adv", False, None),
    (16, "not", "not", "adv", True, None),
    (17, "all", "all", "det", True, None),
    (18, "many", "many", "det", True, None),
    (19, "some", "some", "det", False, None),
    (20, "few", "few", "det", False, None),
    (21, "other", "other", "adj", False, None),
    (22, "one", "one", "num", True, None),
    (23, "two", "two", "num", True, None),
    (24, "three", "three", "num", False, None),
    (25, "four", "four", "num", False, None),
    (26, "five", "five", "num", False, None),
    (27, "big", "big", "adj", True, None),
    (28, "long", "long", "adj", True, None),
    (29, "wide", "wide", "adj", False, None),
    (30, "thick", "thick", "adj", False, None),
    (31, "heavy", "heavy", "adj", False, None),
    (32, "small", "small", "adj", True, None),
    (33, "short", "short", "adj", False, None),
    (34, "narrow", "narrow", "adj", False, None),
    (35, "thin", "thin", "adj", False, None),
    (36, "woman", "woman", "noun", True, None),
    (37, "man", "man (adult male)", "noun", True, r"male|adult"),
    (38, "man", "man (human being)", "noun", True, r"^a human being"),
    (39, "child", "child", "noun", False, None),
    (40, "wife", "wife", "noun", False, None),
    (41, "husband", "husband", "noun", False, None),
    (42, "mother", "mother", "noun", False, None),
    (43, "father", "father", "noun", False, None),
    (44, "animal", "animal", "noun", False, None),
    (45, "fish", "fish", "noun", True, None),
    (46, "bird", "bird", "noun", True, None),
    (47, "dog", "dog", "noun", True, None),
    (48, "louse", "louse", "noun", True, None),
    (49, "snake", "snake", "noun", False, None),
    (50, "worm", "worm", "noun", False, None),
    (51, "tree", "tree", "noun", True, None),
    (52, "forest", "forest", "noun", False, None),
    (53, "stick", "stick", "noun", False, None),
    (54, "fruit", "fruit", "noun", False, None),
    (55, "seed", "seed", "noun", True, None),
    (56, "leaf", "leaf", "noun", True, None),
    (57, "root", "root", "noun", True, None),
    (58, "bark", "bark (of a tree)", "noun", True, r"tree|plant|wood"),
    (59, "flower", "flower", "noun", False, None),
    (60, "grass", "grass", "noun", False, None),
    (61, "rope", "rope", "noun", False, None),
    (62, "skin", "skin", "noun", True, None),
    (63, "meat", "meat", "noun", True, None),
    (64, "blood", "blood", "noun", True, None),
    (65, "bone", "bone", "noun", True, None),
    (66, "fat", "fat (organic substance)", "noun", True, r"substance|grease|oil|tissue|lipid"),
    (67, "egg", "egg", "noun", True, None),
    (68, "horn", "horn", "noun", True, None),
    (69, "tail", "tail", "noun", True, None),
    (70, "feather", "feather", "noun", True, None),
    (71, "hair", "hair", "noun", True, None),
    (72, "head", "head", "noun", True, None),
    (73, "ear", "ear", "noun", True, None),
    (74, "eye", "eye", "noun", True, None),
    (75, "nose", "nose", "noun", True, None),
    (76, "mouth", "mouth", "noun", True, None),
    (77, "tooth", "tooth", "noun", True, None),
    (78, "tongue", "tongue", "noun", True, None),
    (79, "fingernail", "fingernail", "noun", True, None),
    (80, "foot", "foot", "noun", True, None),
    (81, "leg", "leg", "noun", False, None),
    (82, "knee", "knee", "noun", True, None),
    (83, "hand", "hand", "noun", True, None),
    (84, "wing", "wing", "noun", False, None),
    (85, "belly", "belly", "noun", True, None),
    (86, "guts", "guts", "noun", False, None),
    (87, "neck", "neck", "noun", True, None),
    (88, "back", "back", "noun", False, None),
    (89, "breast", "breast", "noun", True, None),
    (90, "heart", "heart", "noun", True, None),
    (91, "liver", "liver", "noun", True, None),
    (92, "drink", "to drink", "verb", True, None),
    (93, "eat", "to eat", "verb", True, None),
    (94, "bite", "to bite", "verb", True, None),
    (95, "suck", "to suck", "verb", False, None),
    (96, "spit", "to spit", "verb", False, None),
    (97, "vomit", "to vomit", "verb", False, None),
    (98, "blow", "to blow", "verb", False, None),
    (99, "breathe", "to breathe", "verb", False, None),
    (100, "laugh", "to laugh", "verb", False, None),
    (101, "see", "to see", "verb", True, None),
    (102, "hear", "to hear", "verb", True, None),
    (103, "know", "to know", "verb", True, None),
    (104, "think", "to think", "verb", False, None),
    (105, "smell", "to smell", "verb", False, None),
    (106, "fear", "to fear", "verb", False, None),
    (107, "sleep", "to sleep", "verb", True, None),
    (108, "live", "to live", "verb", False, None),
    (109, "die", "to die", "verb", True, None),
    (110, "kill", "to kill", "verb", True, None),
    (111, "fight", "to fight", "verb", False, None),
    (112, "hunt", "to hunt", "verb", False, None),
    (113, "hit", "to hit", "verb", False, None),
    (114, "cut", "to cut", "verb", False, None),
    (115, "split", "to split", "verb", False, None),
    (116, "stab", "to stab", "verb", False, None),
    (117, "scratch", "to scratch", "verb", False, None),
    (118, "dig", "to dig", "verb", False, None),
    (119, "swim", "to swim", "verb", True, None),
    (120, "fly", "to fly", "verb", True, None),
    (121, "walk", "to walk", "verb", True, None),
    (122, "come", "to come", "verb", True, None),
    (123, "lie", "to lie (as in a bed)", "verb", True, r"recline|bed|horizontal|rest|flat"),
    (124, "sit", "to sit", "verb", True, None),
    (125, "stand", "to stand", "verb", True, None),
    (126, "turn", "to turn", "verb", False, None),
    (127, "fall", "to fall", "verb", False, None),
    (128, "give", "to give", "verb", True, None),
    (129, "hold", "to hold", "verb", False, None),
    (130, "squeeze", "to squeeze", "verb", False, None),
    (131, "rub", "to rub", "verb", False, None),
    (132, "wash", "to wash", "verb", False, None),
    (133, "wipe", "to wipe", "verb", False, None),
    (134, "pull", "to pull", "verb", False, None),
    (135, "push", "to push", "verb", False, None),
    (136, "throw", "to throw", "verb", False, None),
    (137, "tie", "to tie", "verb", False, None),
    (138, "sew", "to sew", "verb", False, None),
    (139, "count", "to count", "verb", False, None),
    (140, "say", "to say", "verb", True, None),
    (141, "sing", "to sing", "verb", False, None),
    (142, "play", "to play", "verb", False, None),
    (143, "float", "to float", "verb", False, None),
    (144, "flow", "to flow", "verb", False, None),
    (145, "freeze", "to freeze", "verb", False, None),
    (146, "swell", "to swell", "verb", False, None),
    (147, "sun", "sun", "noun", True, None),
    (148, "moon", "moon", "noun", True, None),
    (149, "star", "star", "noun", True, None),
    (150, "water", "water", "noun", True, None),
    (151, "rain", "rain", "noun", True, None),
    (152, "river", "river", "noun", False, None),
    (153, "lake", "lake", "noun", False, None),
    (154, "sea", "sea", "noun", False, None),
    (155, "salt", "salt", "noun", False, None),
    (156, "stone", "stone", "noun", True, None),
    (157, "sand", "sand", "noun", True, None),
    (158, "dust", "dust", "noun", False, None),
    (159, "earth", "earth", "noun", True, r"soil|ground|dirt|land"),
    (160, "cloud", "cloud", "noun", True, None),
    (161, "fog", "fog", "noun", False, None),
    (162, "sky", "sky", "noun", False, None),
    (163, "wind", "wind", "noun", False, None),
    (164, "snow", "snow", "noun", False, None),
    (165, "ice", "ice", "noun", False, None),
    (166, "smoke", "smoke", "noun", True, None),
    (167, "fire", "fire", "noun", True, None),
    (168, "ash", "ash", "noun", True, None),
    (169, "burn", "to burn", "verb", True, None),
    (170, "road", "road", "noun", True, None),
    (171, "mountain", "mountain", "noun", True, None),
    (172, "red", "red", "adj", True, None),
    (173, "green", "green", "adj", True, None),
    (174, "yellow", "yellow", "adj", True, None),
    (175, "white", "white", "adj", True, None),
    (176, "black", "black", "adj", True, None),
    (177, "night", "night", "noun", True, None),
    (178, "day", "day", "noun", False, None),
    (179, "year", "year", "noun", False, None),
    (180, "warm", "warm", "adj", True, None),
    (181, "cold", "cold", "adj", True, None),
    (182, "full", "full", "adj", True, None),
    (183, "new", "new", "adj", True, None),
    (184, "old", "old", "adj", False, None),
    (185, "good", "good", "adj", True, None),
    (186, "bad", "bad", "adj", False, None),
    (187, "rotten", "rotten", "adj", False, None),
    (188, "dirty", "dirty", "adj", False, None),
    (189, "straight", "straight", "adj", False, None),
    (190, "round", "round", "adj", True, None),
    (191, "sharp", "sharp", "adj", False, None),
    (192, "dull", "dull", "adj", False, None),
    (193, "smooth", "smooth", "adj", False, None),
    (194, "wet", "wet", "adj", False, None),
    (195, "dry", "dry", "adj", True, None),
    (196, "correct", "correct", "adj", False, None),
    (197, "near", "near", "adv", False, None),
    (198, "far", "far", "adv", False, None),
    (199, "right", "right", "adj", False, r"direction|side|opposite of left|left"),
    (200, "left", "left", "adj", False, r"direction|side|opposite of right|right"),
    (201, "at", "at", "prep", False, None),
    (202, "in", "in", "prep", False, None),
    (203, "with", "with", "prep", False, None),
    (204, "and", "and", "conj", False, None),
    (205, "if", "if", "conj", False, None),
    (206, "because", "because", "conj", False, None),
    (207, "name", "name", "noun", True, None),
]

ITEMS = [dict(n=n, en=en, label=label, pos=pos, core=core, hint=hint) for n, en, label, pos, core, hint in _RAW]

assert len(ITEMS) == 207 and [i["n"] for i in ITEMS] == list(range(1, 208))
